<<<<<<< HEAD
name: Test os226

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        test:
          - batch
          - pool
          - syscall
          - preempt

    steps:
    - uses: actions/checkout@v2
    - run: make
    - run: ./test/run.sh ${{matrix.test}}
=======

name: Test os226

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        test:
          - exec

    steps:
    - uses: actions/checkout@v2
    - run: make
    - run: ./test/run.sh ${{matrix.test}}
>>>>>>> 056075af091d07941e0d025cdd1392e260add4c3
